import { Dayjs } from 'dayjs';

/**
 * An object containing the information for calendar events
 * This will ignore the autogenerated mongodb '_id' field
 * 
 * @param {string} id The unique UUIDv4 for the event
 * @param {string} eventId The ID assigned by the Google Calendar API to the calendar event
 * @param {"event"|"signup"} type The type of the event
 * @param {string} name The name of the event
 * @param {string} description The description of the event
 * @param {string} club The name of the club that is hosting the event
 * @param {string} start The time in UTC milliseconds that the event starts
 * @param {string} end The time in UTC milliseconds that the event ends
 */
export function Event(id, eventId, type, name, description, club, start, end) {
    this.id = id || '';
    this.eventId = eventId || '';
    this.type = type || 'event';
    this.name = name || '';
    this.description = description || '';
    this.club = club || '';
    this.start = start || '';
    this.end = end || '';
}

/**
 * An object containing the information for a club
 * @param {string} name The name of the club
 * @param {boolean} advised True if an advised club, otherwise false for independent club
 * @param {string} fb Link to facebook page
 * @param {string} website Link to website
 * @param {string} coverImgThumbnail URL of cover image thumbnail
 * @param {string} coverImg URL of the full-sized cover image
 * @param {string} description Description of the club
 * @param {Exec[]} execs Array of exec objects
 * @param {Committee[]} committees Array of committee objects
 * @param {Object} coverImgBlobs Base64 encoded strings of the cover image
 * @param {string} coverImgBlobs.img The compressed cover image
 * @param {string} coverImgBlobs.thumb The super compressed cover image thumbnail
 * @param {string[]} execProfilePicBlobs Base64 encoded strings of the exec profile pics in the order of the execs (null if missing)
 */
export function Club(
    name,
    advised,
    fb,
    website,
    coverImgThumbnail,
    coverImg,
    description,
    execs,
    committees,
    coverImgBlobs = null,
    execProfilePicBlobs = null,
) {
    this.name = name || '';
    this.advised = advised || false;
    this.fb = fb || '';
    this.website = website || '';
    this.coverImgThumbnail = coverImgThumbnail || '';
    this.coverImg = coverImg || '';
    this.description = description || '';
    this.execs = execs || [new Exec()];
    this.committees = committees || [new Committee()];
    this.coverImgBlobs = coverImgBlobs || [];
    this.execProfilePicBlobs = execProfilePicBlobs || [];
}

/**
 * An object containing the basic information for a club, to be displayed in the list view of all clubs
 * @param {string} objId The unique ID to match the info and data objects
 * @param {string} name The name of the club
 * @param {boolean} advised True if an advised club, otherwise false for independent club
 * @param {string} fb Link to facebook page
 * @param {string} website Link to website
 * @param {string} coverImgThumbnail URL of cover image thumbnail
 */
export function ClubInfo(objId, name, advised, fb, website, coverImgThumbnail) {
    this.objId = objId;
    this.name = name;
    this.advised = advised;
    this.fb = fb;
    this.website = website;
    this.coverImgThumbnail = coverImgThumbnail;
}

/**
 * An object containing the data for a club
 * @param {string} objId The unique ID to match the info and data objects
 * @param {string} infoId ID of the club, used for getting full club info
 * @param {string} description Description of the club
 * @param {Exec[]} execs Array of exec objects
 * @param {Committee[]} committee Array of committee objects
 * @param {string} coverImg URL of the full-sized cover image
 */
export function ClubData(infoId, description, execs, committee, coverImg) {
    this.objId = objId;
    this.infoId = infoId;
    this.description = description;
    this.execs = execs;
    this.committee = committee;
    this.coverImg = coverImg;
}

/**
 * An object containing the information for a volunteering opportunity
 * @param {string} name The name of the volunteering opportunity
 * @param {string} club The club name that is offering the volunteering opportunity
 * @param {string} description Description of the volunteering opportunity
 * @param {Object} filters Object used for filtering volunteering opportunities
 * @param {boolean} filters.limited True if limited slots, otherwise false
 * @param {boolean} filters.senester True if semester long sommitment, otherwise false
 * @param {boolean} filters.setTimes True if set volunteering time, otherwise false
 * @param {boolean} filters.weekly True if there are weekly signups, otherwise false
 * @param {boolean} filters.open True if volunteering opportunity is currently available, otherwise false
 * @param {string} signupTime Time of weekly signups, null if no weekly signups
 */
export function Volunteering(name, club, description, filters, signupTime) {
    this.name = name || '';
    this.club = club || '';
    this.description = description || '';
    this.filters = filters || { limited: false, semester: false, setTimes: false, weekly: false, open: true };
    this.signupTime = signupTime || '';
}

/**
 * An object containing the information of an exec
 * @param {string} name The name of the exec
 * @param {string} position The postition of the exec
 * @param {string} description The description of the exec
 * @param {string} img The image URL of the exec
 */
export function Exec(name, position, description, img) {
    this.name = name || '';
    this.position = position || '';
    this.description = description || '';
    this.img = img || '';
}

/**
 * An object containing the information of a committee
 * @param {string} name The name of the committee
 * @param {string} description The description for the committee
 * @param {string} fb The facebook link of the committee
 * @param {string} website The website link of the committee
 */
export function Committee(name, description, fb, website) {
    this.name = name || '';
    this.description = description || '';
    this.fb = fb || '';
    this.website = website || '';
}

/**
 * Return object for fetch requests
 * @param {number} status The HTTP status code
 * @param {object} data Data of the request
 */
export function FetchResponse(status, data) {
    this.status = status;
    this.data = data;
}

/**
 * Holds the list of numbered dates for the calendar to +/- 1 month
 *
 * @param {number[]} current List of dates in the current month
 * @param {number[]} previous List of dates in the previous month
 * @param {number[]} next List of dates in the next month
 * @param {Dayjs} dayObj The dayjs object containing the current date
 */
export function CalendarDates(current, previous, next, dayObj) {
    this.current = current;
    this.previous = previous;
    this.next = next;
    this.dayObj = dayObj;
}

/**
 * A date divider object to be parsed by the home event list creator
 * The object ID will be set to an empty string to differentiate
 * between the EventInfo objects
 *
 * @param {string} date Date formatted as YYYY-MM-DD
 */
export function DateDivider(date) {
    this.date = date;
    this.id = '';
}

/**
 * @typedef {Object} DateAndTime
 * @property {string} date The date in the format (YYYY-MM-DD)
 * @property {string} time The time in the format (HH:MM)
 */
