name: Build Docs
on:
    push:
        branches:
            - master
            - action-test
permissions:
    contents: write

jobs:
    build-docs:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v5

            - name: Install and Build 🔧
              run: |
                  corepack enable
                  yarn install
                  yarn docs

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: docs # The folder the action should deploy.
