name: 'Run Tests and Checks'

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    types:
        name: Perform Type Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use NodeJS 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  
            - name: Enable corepack
              run: corepack enable

            - name: Setup repo
              env:
                  ENV: ${{ secrets.STAGING_ENV }}
              run: |
                  cd $GITHUB_WORKSPACE/server && echo "$ENV" >| .env
                  cd .. && yarn install --immutable

            - name: Client type check
              run: cd $GITHUB_WORKSPACE && yarn type

            - name: Server type check
              run: cd $GITHUB_WORKSPACE && yarn type:server
